name: 中青邀请阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 0-23/3 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/CiQii/youthShare.git ~/youthShare
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/youthShare
          npm install
          npm install md5-node
      - name: '运行 【中青邀请阅读】'
        run: |
          cd ~/youthShare   
          node Task/youthshare.js
